Added convert files + unit tests
tir-bogo/BeoAnalyzer pull request #1
Opened 2019-03-13 10:04 UTC by tir-bogo

Added feature to convert files using same standard as the previous Log tool in c#

2019-03-13 11:11 UTC, pkhbogo requested changes
A few minor things.

2019-03-13 11:11 UTC, pkhbogo commented on logfile/operations/types/convert_files.py
> +from logfile.operations.operation_base import OperationBase
Consider just using "operation_base". You don't need the entire package "path" when in same package.

2019-03-13 11:11 UTC, pkhbogo commented on logfile/operations/types/convert_files.py
> +        OperationBase.__init__(self)
`super().__init__()`?

2019-03-13 11:11 UTC, pkhbogo commented on logfile/operations/types/convert_files.py
> +            if val.lower() in item.lower():
Are you sure that's what you want?

2019-03-13 11:11 UTC, pkhbogo commented on logfile/operations/types/convert_files.py
> +        new_file = Path(path.parents[0], path.name + new_extension)
Consider using Path.rename instead.

2019-03-13 11:11 UTC, pkhbogo commented on logfile/operations/types/convert_files.py
> +        """
Hhhhmmmm.... this means that in order to make sure that you don't get an exception, the caller /must/ check the validity before calling run. If it's ok by you, then ok, but at least document it :-)

2019-03-14 12:10 UTC, tir-bogo commented on logfile/operations/types/convert_files.py
> +        """
I can make it return True if it run successfully, and False if there was some error so it could not run.

2019-03-14 12:10 UTC, tir-bogo commented on logfile/operations/types/convert_files.py
> +        OperationBase.__init__(self)
Fixed (y)

2019-03-14 12:10 UTC, tir-bogo commented on logfile/operations/types/convert_files.py
> +            if val.lower() in item.lower():
Fixed

2019-03-14 12:11 UTC, tir-bogo commented on logfile/operations/types/convert_files.py
> +        new_file = Path(path.parents[0], path.name + new_extension)
Fixed

2019-03-14 12:27 UTC, tir-bogo commented on logfile/operations/types/convert_files.py
> +        """
I tried to make some changes, what do you think?

2019-03-14 13:23 UTC, merged